name: Daily update of stubs from typeshed to PyPI

on:
  # Triggers the workflow every three hours starting midnight UTC.
  schedule:
    - cron: 0 */3 * * *
  # If needed, allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout typeshed
        uses: actions/checkout@v2
        with:
          repository: python/typeshed
          path: typeshed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine toml reuests
      - name: Execute diff build and upload tasks
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TYPESHED_BOT_API_TOKEN }}
        run: |
          cd typeshed
          PYTHONPATH=../main python -m scripts.upload_changed $(cat ../main/data/last_typeshed_commit.sha1) --dry-run
          git rev-parse HEAD > ../main/data/last_typeshed_commit.sha1
          cd ../main
          git config user.name github-actions && git config user.email github-actions@github.com
          git add . && git commit -m "Update last typeshed commit" && git push
