name: Daily update of stubs from typeshed to PyPI

on:
  # Triggers the workflow daily at 2PM UTC.
  schedule:
    - cron: 0 14 * * *
  # If needed, allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Execute diff build and upload tasks
        run: |
          echo "WIP..."
          git config user.name github-actions
          git config user.email github-actions@github.com
          git clone https://github.com/python/typeshed
          cd typeshed
          git rev-parse HEAD > ../last_typeshed_commit.sha1
          cd ..
          rm -rf typeshed
          git add .
          git commit -m "Update last typeshed commit"
          git push
          echo "Done."
