name: Daily update of stubs from typeshed to PyPI

on:
  # Triggers the workflow every three hours starting midnight UTC.
  schedule:
    - cron: 0 */3 * * *
  # If needed, allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout typeshed
        uses: actions/checkout@v2
        with:
          repository: python/typeshed
          path: typeshed

      - name: Execute diff build and upload tasks
        run: |
          echo "WIP..."
          cd typeshed
          git rev-parse HEAD > ../main/data/last_typeshed_commit.sha1
          cd ../main
          git config user.name github-actions && git config user.email github-actions@github.com
          git add . && git commit -m "Update last typeshed commit" && git push
          echo "Done."
